### ISSUE TITLE
[FEATURE]: Fix some errors in swagger

### ISSUE THREAD

**Issue by cornhubius** [meetingbook/meetingbook#122]
## Description

Fix some errors in swagger

**!!! If you know any mistakes, then add them in the comments. !!!**

**Comment by DramaTourG** [comment]
I suggest sending to /schedule json. it will be easier to add multiple slots at once

**Comment by cornhubius** [comment]
GET /calendars/{link_id}/bookings/{booking_id}
add response 404 BAD REQUEST

**Comment by cornhubius** [comment]
> /registration-> post-> description fix description

done
