### ISSUE TITLE
[FEATURE] Admin Logins to the MeetingBook

### ISSUE THREAD

**Issue by mentortechabc** [meetingbook/meetingbook#32]
## Description

**As an** admin 
**I want to be able to** login to my MeetingBook account 
**So that** I can manage my availabilities in calendar 

#### Scenario 1: Successful login

**Given** Admin enters a valid email address 
  **And** Admin enters a valid password 
  **And** email and password match 
**When**  Admin clicks Login button 
**Then**  Admin should be logged in to the admin panel 
  **And** Admin see a message about successful login

#### Scenario 2: Failed login

**Given** Admin enters a invalid email address
  **Or** Admin enters a invalid password
  **And** Email and password don't match 
**When**  Admin clicks Login button 
**Then**  Admin should **not** be logged in 
  **And** Admin see a error message

**Comment by glebhg** [comment]
won't fix :)

**Comment by mentortechabc** [comment]
user stories are handled in sprint description
