### ISSUE TITLE
[FEATURE]: Borrow design for MeetingBook Web Application

### ISSUE THREAD

**Issue by glebhg** [meetingbook/meetingbook#5]
## Description

- Google similar apps
- Check App Store and Google Play
- Check [https://dribbble.com/](https://dribbble.com/)

Result: create a mood board in Figma (https://milanote.com/guide/create-better-moodboards).

TODO: make a survey

**Comment by NatalliaMil** [comment]
https://www.figma.com/file/5VT9KAPYNSFn8AkVm6f4tp/Design-for-MeetingBook-Web-Application?node-id=0%3A1

**Comment by glebhg** [comment]
WE NEED MATERIAL UI BASED DESIGN!

**Comment by glebhg** [comment]
The result of this issue must be a Figma page with design elements.

**Comment by glebhg** [comment]
https://www.figma.com/file/LSKPBAnOkYg5odtGwC0yIb/MeetingBook-Design-Kit?node-id=0%3A10
