### ISSUE TITLE
[FEATURE] Frontend sends login requests to backend and displays the results 

### ISSUE THREAD

**Issue by mentortechabc** [meetingbook/meetingbook#56]
## Description

Frontend sends login requests to backend and displays the results of credentials checking.

## Describe the solution you'd like

After a user enters credentials and submits a login form the frontend interacts with a backend and displays if the login was successful.

See also https://github.com/meetingbook/meetingbook/wiki/MeetingBook-User-Stories#story-1--admin-logins-to-the-meetingbook

## Acceptance criteria
* [ ] Update readme. How to run BE and FE together.
* [x] [Login page](https://github.com/meetingbook/meetingbook/issues/12) can send requests to backend 
* [x] If login is successful, redirect to admin's page. Otherwise - show error.

## Hints
* [x] Find out about CORS

**Comment by glebhg** [comment]
Regarding CORS consider the following:

1. add `flask_cors` to requirements.txt
2. use it in code:
```python
from flask import Flask
from flask_cors import CORS
app = Flask(__name__)
CORS(app)
```

So the web application can call REST API from any port.

**Comment by leopardilla** [comment]
[Short Summary and useful links] (https://docs.google.com/document/d/1p85HrnkwpUuse51wGJLLvO4_BmuSRE4FVtgnQbELYa8/edit?usp=sharing)

**Comment by mentortechabc** [comment]
By the end of the week we want to use React to send request from the Frontend to the backend. 
100%
