### ISSUE TITLE
[FEATURE]: create design for registration screen

### ISSUE THREAD

**Issue by glebhg** [meetingbook/meetingbook#77]
## Description

Create/steal the design for registration screen.

## Describe the solution you'd like

- dribbble?
- the result must be a Figma screen

related to https://github.com/meetingbook/meetingbook/wiki/MeetingBook-User-Stories#story-0--admin-sign-up-to-the-meetingbook

**Comment by NatalliaMil** [comment]
https://www.figma.com/file/LSKPBAnOkYg5odtGwC0yIb/MeetingBook-Design-Kit?node-id=0%3A10
